
package com.mycompany.ads1001.t2;

/**
 *
 * @author Breno e Bia
 */
public class TelaInicial extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaInicial.class.getName());

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAbrirCompra = new javax.swing.JButton();
        btnAbrirProduto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Tela_inicial_maua_na_chapa (2).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnAbrirCompra.setText("\n");
        btnAbrirCompra.addActionListener(this::btnAbrirCompraActionPerformed);
        getContentPane().add(btnAbrirCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 370, 80));

        btnAbrirProduto.addActionListener(this::btnAbrirProdutoActionPerformed);
        getContentPane().add(btnAbrirProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 370, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAbrirCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirCompraActionPerformed
        TelaDePedidos telaPed = new TelaDePedidos();
        telaPed.setVisible(true);
        telaPed.setLocationRelativeTo(null);

        this.dispose(); // Fecha APENAS a tela onde o botão foi clicado        // TODO add your handling code here:
    }//GEN-LAST:event_btnAbrirCompraActionPerformed

    private void btnAbrirProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirProdutoActionPerformed
        CadastroProduto telaCadastro = new CadastroProduto();
        telaCadastro.setVisible(true);
        telaCadastro.setLocationRelativeTo(null);

        this.dispose();  // TODO add your handling code here:
    }//GEN-LAST:event_btnAbrirProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaInicial().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrirCompra;
    private javax.swing.JButton btnAbrirProduto;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
